/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Run;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RunResults
 */
public class RunResultsTest {
    private final RunResults model = new RunResults();

    /**
     * Model tests for RunResults
     */
    @Test
    public void testRunResults() {
        // TODO: test RunResults
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    public void pageNumberTest() {
        // TODO: test pageNumber
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'numPages'
     */
    @Test
    public void numPagesTest() {
        // TODO: test numPages
    }

    /**
     * Test the property 'amountOfRuns'
     */
    @Test
    public void amountOfRunsTest() {
        // TODO: test amountOfRuns
    }

    /**
     * Test the property 'runs'
     */
    @Test
    public void runsTest() {
        // TODO: test runs
    }

}
