/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TestRun
 */
public class TestRunTest {
    private final TestRun model = new TestRun();

    /**
     * Model tests for TestRun
     */
    @Test
    public void testTestRun() {
        // TODO: test TestRun
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'group'
     */
    @Test
    public void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'test'
     */
    @Test
    public void testTest() {
        // TODO: test test
    }

    /**
     * Test the property 'bundleName'
     */
    @Test
    public void bundleNameTest() {
        // TODO: test bundleName
    }

    /**
     * Test the property 'testName'
     */
    @Test
    public void testNameTest() {
        // TODO: test testName
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'queued'
     */
    @Test
    public void queuedTest() {
        // TODO: test queued
    }

    /**
     * Test the property 'requestor'
     */
    @Test
    public void requestorTest() {
        // TODO: test requestor
    }

    /**
     * Test the property 'stream'
     */
    @Test
    public void streamTest() {
        // TODO: test stream
    }

    /**
     * Test the property 'repo'
     */
    @Test
    public void repoTest() {
        // TODO: test repo
    }

    /**
     * Test the property 'obr'
     */
    @Test
    public void obrTest() {
        // TODO: test obr
    }

    /**
     * Test the property 'rerun'
     */
    @Test
    public void rerunTest() {
        // TODO: test rerun
    }

    /**
     * Test the property 'rerunReason'
     */
    @Test
    public void rerunReasonTest() {
        // TODO: test rerunReason
    }

    /**
     * Test the property 'local'
     */
    @Test
    public void localTest() {
        // TODO: test local
    }

    /**
     * Test the property 'trace'
     */
    @Test
    public void traceTest() {
        // TODO: test trace
    }

    /**
     * Test the property 'rasRunId'
     */
    @Test
    public void rasRunIdTest() {
        // TODO: test rasRunId
    }

}
