/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TestMethod
 */
public class TestMethodTest {
    private final TestMethod model = new TestMethod();

    /**
     * Model tests for TestMethod
     */
    @Test
    public void testTestMethod() {
        // TODO: test TestMethod
    }

    /**
     * Test the property 'className'
     */
    @Test
    public void classNameTest() {
        // TODO: test className
    }

    /**
     * Test the property 'methodName'
     */
    @Test
    public void methodNameTest() {
        // TODO: test methodName
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'runLogStart'
     */
    @Test
    public void runLogStartTest() {
        // TODO: test runLogStart
    }

    /**
     * Test the property 'runLogEnd'
     */
    @Test
    public void runLogEndTest() {
        // TODO: test runLogEnd
    }

    /**
     * Test the property 'befores'
     */
    @Test
    public void beforesTest() {
        // TODO: test befores
    }

    /**
     * Test the property 'afters'
     */
    @Test
    public void aftersTest() {
        // TODO: test afters
    }

}
