/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TestClass
 */
public class TestClassTest {
    private final TestClass model = new TestClass();

    /**
     * Model tests for TestClass
     */
    @Test
    public void testTestClass() {
        // TODO: test TestClass
    }

    /**
     * Test the property 'testclass'
     */
    @Test
    public void testclassTest() {
        // TODO: test testclass
    }

    /**
     * Test the property 'bundle'
     */
    @Test
    public void bundleTest() {
        // TODO: test bundle
    }

}
