/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TestRunRequest
 */
public class TestRunRequestTest {
    private final TestRunRequest model = new TestRunRequest();

    /**
     * Model tests for TestRunRequest
     */
    @Test
    public void testTestRunRequest() {
        // TODO: test TestRunRequest
    }

    /**
     * Test the property 'classNames'
     */
    @Test
    public void classNamesTest() {
        // TODO: test classNames
    }

    /**
     * Test the property 'requestorType'
     */
    @Test
    public void requestorTypeTest() {
        // TODO: test requestorType
    }

    /**
     * Test the property 'requestor'
     */
    @Test
    public void requestorTest() {
        // TODO: test requestor
    }

    /**
     * Test the property 'testStream'
     */
    @Test
    public void testStreamTest() {
        // TODO: test testStream
    }

    /**
     * Test the property 'obr'
     */
    @Test
    public void obrTest() {
        // TODO: test obr
    }

    /**
     * Test the property 'mavenRepository'
     */
    @Test
    public void mavenRepositoryTest() {
        // TODO: test mavenRepository
    }

    /**
     * Test the property 'sharedEnvironmentPhase'
     */
    @Test
    public void sharedEnvironmentPhaseTest() {
        // TODO: test sharedEnvironmentPhase
    }

    /**
     * Test the property 'sharedEnvironmentRunName'
     */
    @Test
    public void sharedEnvironmentRunNameTest() {
        // TODO: test sharedEnvironmentRunName
    }

    /**
     * Test the property 'overrides'
     */
    @Test
    public void overridesTest() {
        // TODO: test overrides
    }

    /**
     * Test the property 'trace'
     */
    @Test
    public void traceTest() {
        // TODO: test trace
    }

}
