/*
 * Copyright contributors to the Galasa project
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/* Generated By:JJTree: Do not edit this line. ASTConstant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package dev.galasa.framework.internal.rps.tree;

public
class ASTConstant extends SimpleNode {
  public ASTConstant(int id) {
    super(id);
  }

  public ASTConstant(RpsResolver p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ae63c4b066ced513973e4cf257418b0b (do not edit this line) */
