/*
 * Copyright contributors to the Galasa project
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/* Generated By:JJTree: Do not edit this line. ASTMultiRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package dev.galasa.framework.internal.rps.tree;

public
class ASTMultiRange extends SimpleNode {
  public ASTMultiRange(int id) {
    super(id);
  }

  public ASTMultiRange(RpsResolver p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e75753a1834e0869db78c80482c3ce35 (do not edit this line) */
