/*
 * Copyright contributors to the Galasa project
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/* Generated By:JJTree: Do not edit this line. ASTSingleRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package dev.galasa.framework.internal.rps.tree;

public
class ASTSingleRange extends SimpleNode {
  public ASTSingleRange(int id) {
    super(id);
  }

  public ASTSingleRange(RpsResolver p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=81bb08e618295a75894e0970349e6c30 (do not edit this line) */
