/*
 * Copyright contributors to the Galasa project
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/* Generated By:JJTree&JavaCC: Do not edit this line. RpsResolverConstants.java */
package dev.galasa.framework.internal.rps.tree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RpsResolverConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHARACTER = 1;
  /** RegularExpression Id. */
  int LEFTBRACKET = 2;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 3;
  /** RegularExpression Id. */
  int BETWEEN = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CHARACTER>",
    "\"{\"",
    "\"}\"",
    "\"-\"",
  };

}
