/*
 * Copyright contributors to the Galasa project
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/* Generated By:JavaCC: Do not edit this line. RpsResolverTreeConstants.java Version 5.0 */
package dev.galasa.framework.internal.rps.tree;

public interface RpsResolverTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCONSTANT = 1;
  public int JJTVARIABLE = 2;
  public int JJTSINGLERANGE = 3;
  public int JJTMULTIRANGE = 4;


  public String[] jjtNodeName = {
    "Start",
    "Constant",
    "Variable",
    "SingleRange",
    "MultiRange",
  };
}
/* JavaCC - OriginalChecksum=3acd190491dc41d1930e42f1ffb53e9f (do not edit this line) */
