@startuml personal-access-token-flow
title "Authentication flow when requesting a new personal access token"

actor User
participant WebUI as "Web UI"
participant AuthAPI as "Auth API"
participant Dex

User -> WebUI: Requests personal access token
activate WebUI

WebUI -> AuthAPI: POST /auth/clients with "Authorization: Bearer <JWT>" header
activate AuthAPI
AuthAPI -> AuthAPI: Check "Authorization" header contains a valid JWT
AuthAPI -> Dex: gRPC call to createClient()
activate Dex
Dex --> AuthAPI: Success response (client_id, client_secret)
deactivate Dex
AuthAPI --> WebUI: Success response (client_id, client_secret)
deactivate AuthAPI

WebUI -> AuthAPI: GET /auth?client_id=myclient&callback_url=http://webui-hostname/callback
activate AuthAPI
note left
The following is identical to the
initial authentication flow, but
the client_id used will be the ID
of the newly created Dex client.
end note

AuthAPI -> Dex: GET /auth?client_id=myclient&scope=...&state=somestate&redirect_uri=http://galasa-api/auth/callback
activate Dex
Dex --> AuthAPI: Redirect to /auth/callback?code=someauthcode&state=somestate
deactivate Dex
AuthAPI --> WebUI: Redirect to http://webui-hostname/callback?code=someauthcode
deactivate AuthAPI
note left
The redirect's location is the
same "callback_url" provided
in the GET /auth request.
end note

WebUI -> AuthAPI: POST /auth (client_id, client_secret, code)
activate AuthAPI
AuthAPI -> Dex: POST /token (client_id, client_secret, code)
activate Dex
Dex --> AuthAPI: Success response (JWT, refresh token)
deactivate Dex
AuthAPI --> WebUI: Success response (JWT, refresh token)
deactivate AuthAPI

WebUI --> User: Displays personal access token details
deactivate WebUI
@enduml