/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.TestRunRequest;
import org.openapitools.client.model.TestRuns;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class RunsApiApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public RunsApiApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RunsApiApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getRunsGroup
     * @param groupId Run Group ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run Info </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunsGroupCall(String groupId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runs/{groupId}"
            .replaceAll("\\{" + "groupId" + "\\}", localVarApiClient.escapeString(groupId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRunsGroupValidateBeforeCall(String groupId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupId' is set
        if (groupId == null) {
            throw new ApiException("Missing the required parameter 'groupId' when calling getRunsGroup(Async)");
        }
        

        okhttp3.Call localVarCall = getRunsGroupCall(groupId, _callback);
        return localVarCall;

    }

    /**
     * Get group runs
     * 
     * @param groupId Run Group ID (required)
     * @return TestRuns
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run Info </td><td>  -  </td></tr>
     </table>
     */
    public TestRuns getRunsGroup(String groupId) throws ApiException {
        ApiResponse<TestRuns> localVarResp = getRunsGroupWithHttpInfo(groupId);
        return localVarResp.getData();
    }

    /**
     * Get group runs
     * 
     * @param groupId Run Group ID (required)
     * @return ApiResponse&lt;TestRuns&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run Info </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TestRuns> getRunsGroupWithHttpInfo(String groupId) throws ApiException {
        okhttp3.Call localVarCall = getRunsGroupValidateBeforeCall(groupId, null);
        Type localVarReturnType = new TypeToken<TestRuns>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get group runs (asynchronously)
     * 
     * @param groupId Run Group ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run Info </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunsGroupAsync(String groupId, final ApiCallback<TestRuns> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRunsGroupValidateBeforeCall(groupId, _callback);
        Type localVarReturnType = new TypeToken<TestRuns>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postSubmitTestRuns
     * @param groupId Run Group ID (required)
     * @param testRunRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Test Submitted </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postSubmitTestRunsCall(String groupId, TestRunRequest testRunRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = testRunRequest;

        // create path and map variables
        String localVarPath = "/runs/{groupId}"
            .replaceAll("\\{" + "groupId" + "\\}", localVarApiClient.escapeString(groupId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postSubmitTestRunsValidateBeforeCall(String groupId, TestRunRequest testRunRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupId' is set
        if (groupId == null) {
            throw new ApiException("Missing the required parameter 'groupId' when calling postSubmitTestRuns(Async)");
        }
        
        // verify the required parameter 'testRunRequest' is set
        if (testRunRequest == null) {
            throw new ApiException("Missing the required parameter 'testRunRequest' when calling postSubmitTestRuns(Async)");
        }
        

        okhttp3.Call localVarCall = postSubmitTestRunsCall(groupId, testRunRequest, _callback);
        return localVarCall;

    }

    /**
     * Sumbit test runs
     * 
     * @param groupId Run Group ID (required)
     * @param testRunRequest  (required)
     * @return TestRuns
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Test Submitted </td><td>  -  </td></tr>
     </table>
     */
    public TestRuns postSubmitTestRuns(String groupId, TestRunRequest testRunRequest) throws ApiException {
        ApiResponse<TestRuns> localVarResp = postSubmitTestRunsWithHttpInfo(groupId, testRunRequest);
        return localVarResp.getData();
    }

    /**
     * Sumbit test runs
     * 
     * @param groupId Run Group ID (required)
     * @param testRunRequest  (required)
     * @return ApiResponse&lt;TestRuns&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Test Submitted </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TestRuns> postSubmitTestRunsWithHttpInfo(String groupId, TestRunRequest testRunRequest) throws ApiException {
        okhttp3.Call localVarCall = postSubmitTestRunsValidateBeforeCall(groupId, testRunRequest, null);
        Type localVarReturnType = new TypeToken<TestRuns>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Sumbit test runs (asynchronously)
     * 
     * @param groupId Run Group ID (required)
     * @param testRunRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Test Submitted </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postSubmitTestRunsAsync(String groupId, TestRunRequest testRunRequest, final ApiCallback<TestRuns> _callback) throws ApiException {

        okhttp3.Call localVarCall = postSubmitTestRunsValidateBeforeCall(groupId, testRunRequest, _callback);
        Type localVarReturnType = new TypeToken<TestRuns>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
