/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.JsonError;
import org.openapitools.client.model.Worklist;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class WebUiWorklistApiApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public WebUiWorklistApiApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WebUiWorklistApiApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addWebuiWorklistRunId
     * @param runId Run ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run added to Worklist and updated Worklist returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Run not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addWebuiWorklistRunIdCall(String runId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webui/worklist";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (runId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("runId", runId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addWebuiWorklistRunIdValidateBeforeCall(String runId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'runId' is set
        if (runId == null) {
            throw new ApiException("Missing the required parameter 'runId' when calling addWebuiWorklistRunId(Async)");
        }
        

        okhttp3.Call localVarCall = addWebuiWorklistRunIdCall(runId, _callback);
        return localVarCall;

    }

    /**
     * Add RAS runId to Worklist
     * 
     * @param runId Run ID (required)
     * @return Worklist
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run added to Worklist and updated Worklist returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Run not found </td><td>  -  </td></tr>
     </table>
     */
    public Worklist addWebuiWorklistRunId(String runId) throws ApiException {
        ApiResponse<Worklist> localVarResp = addWebuiWorklistRunIdWithHttpInfo(runId);
        return localVarResp.getData();
    }

    /**
     * Add RAS runId to Worklist
     * 
     * @param runId Run ID (required)
     * @return ApiResponse&lt;Worklist&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run added to Worklist and updated Worklist returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Run not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Worklist> addWebuiWorklistRunIdWithHttpInfo(String runId) throws ApiException {
        okhttp3.Call localVarCall = addWebuiWorklistRunIdValidateBeforeCall(runId, null);
        Type localVarReturnType = new TypeToken<Worklist>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add RAS runId to Worklist (asynchronously)
     * 
     * @param runId Run ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run added to Worklist and updated Worklist returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Run not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addWebuiWorklistRunIdAsync(String runId, final ApiCallback<Worklist> _callback) throws ApiException {

        okhttp3.Call localVarCall = addWebuiWorklistRunIdValidateBeforeCall(runId, _callback);
        Type localVarReturnType = new TypeToken<Worklist>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteWebuiWorklistRunId
     * @param runId Run Id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run removed from Worklist and updated Worklist returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Run not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWebuiWorklistRunIdCall(String runId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webui/worklist";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (runId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("runId", runId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteWebuiWorklistRunIdValidateBeforeCall(String runId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'runId' is set
        if (runId == null) {
            throw new ApiException("Missing the required parameter 'runId' when calling deleteWebuiWorklistRunId(Async)");
        }
        

        okhttp3.Call localVarCall = deleteWebuiWorklistRunIdCall(runId, _callback);
        return localVarCall;

    }

    /**
     * Remove RAS runId from Worklist
     * 
     * @param runId Run Id (required)
     * @return Worklist
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run removed from Worklist and updated Worklist returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Run not found </td><td>  -  </td></tr>
     </table>
     */
    public Worklist deleteWebuiWorklistRunId(String runId) throws ApiException {
        ApiResponse<Worklist> localVarResp = deleteWebuiWorklistRunIdWithHttpInfo(runId);
        return localVarResp.getData();
    }

    /**
     * Remove RAS runId from Worklist
     * 
     * @param runId Run Id (required)
     * @return ApiResponse&lt;Worklist&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run removed from Worklist and updated Worklist returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Run not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Worklist> deleteWebuiWorklistRunIdWithHttpInfo(String runId) throws ApiException {
        okhttp3.Call localVarCall = deleteWebuiWorklistRunIdValidateBeforeCall(runId, null);
        Type localVarReturnType = new TypeToken<Worklist>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Remove RAS runId from Worklist (asynchronously)
     * 
     * @param runId Run Id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Run removed from Worklist and updated Worklist returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Run not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWebuiWorklistRunIdAsync(String runId, final ApiCallback<Worklist> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteWebuiWorklistRunIdValidateBeforeCall(runId, _callback);
        Type localVarReturnType = new TypeToken<Worklist>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getWebuiWorklist
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of Worklist objects </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getWebuiWorklistCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webui/worklist";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getWebuiWorklistValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = getWebuiWorklistCall(_callback);
        return localVarCall;

    }

    /**
     * Get the users Worklist
     * 
     * @return Worklist
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of Worklist objects </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public Worklist getWebuiWorklist() throws ApiException {
        ApiResponse<Worklist> localVarResp = getWebuiWorklistWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get the users Worklist
     * 
     * @return ApiResponse&lt;Worklist&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of Worklist objects </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Worklist> getWebuiWorklistWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getWebuiWorklistValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<Worklist>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get the users Worklist (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of Worklist objects </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getWebuiWorklistAsync(final ApiCallback<Worklist> _callback) throws ApiException {

        okhttp3.Call localVarCall = getWebuiWorklistValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<Worklist>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
