/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ResultNames
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-23T09:56:25.063401+01:00[Europe/London]")
public class ResultNames {
  public static final String SERIALIZED_NAME_RESULTNAMES = "resultnames";
  @SerializedName(SERIALIZED_NAME_RESULTNAMES)
  private List<String> resultnames = null;

  public ResultNames() {
  }

  public ResultNames resultnames(List<String> resultnames) {
    
    this.resultnames = resultnames;
    return this;
  }

  public ResultNames addResultnamesItem(String resultnamesItem) {
    if (this.resultnames == null) {
      this.resultnames = new ArrayList<>();
    }
    this.resultnames.add(resultnamesItem);
    return this;
  }

   /**
   * Get resultnames
   * @return resultnames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getResultnames() {
    return resultnames;
  }


  public void setResultnames(List<String> resultnames) {
    this.resultnames = resultnames;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultNames resultNames = (ResultNames) o;
    return Objects.equals(this.resultnames, resultNames.resultnames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultnames);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultNames {\n");
    sb.append("    resultnames: ").append(toIndentedString(resultnames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("resultnames");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ResultNames
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ResultNames.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResultNames is not found in the empty JSON string", ResultNames.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ResultNames.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResultNames` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if ((jsonObj.get("resultnames") != null && !jsonObj.get("resultnames").isJsonNull()) && !jsonObj.get("resultnames").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `resultnames` to be an array in the JSON string but got `%s`", jsonObj.get("resultnames").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResultNames.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResultNames' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResultNames> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResultNames.class));

       return (TypeAdapter<T>) new TypeAdapter<ResultNames>() {
           @Override
           public void write(JsonWriter out, ResultNames value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResultNames read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ResultNames given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ResultNames
  * @throws IOException if the JSON string is invalid with respect to ResultNames
  */
  public static ResultNames fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResultNames.class);
  }

 /**
  * Convert an instance of ResultNames to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

