/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TestClass
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-23T09:56:25.063401+01:00[Europe/London]")
public class TestClass {
  public static final String SERIALIZED_NAME_TESTCLASS = "testclass";
  @SerializedName(SERIALIZED_NAME_TESTCLASS)
  private String testclass;

  public static final String SERIALIZED_NAME_BUNDLE = "bundle";
  @SerializedName(SERIALIZED_NAME_BUNDLE)
  private String bundle;

  public TestClass() {
  }

  public TestClass testclass(String testclass) {
    
    this.testclass = testclass;
    return this;
  }

   /**
   * Get testclass
   * @return testclass
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTestclass() {
    return testclass;
  }


  public void setTestclass(String testclass) {
    this.testclass = testclass;
  }


  public TestClass bundle(String bundle) {
    
    this.bundle = bundle;
    return this;
  }

   /**
   * Get bundle
   * @return bundle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBundle() {
    return bundle;
  }


  public void setBundle(String bundle) {
    this.bundle = bundle;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestClass testClass = (TestClass) o;
    return Objects.equals(this.testclass, testClass.testclass) &&
        Objects.equals(this.bundle, testClass.bundle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testclass, bundle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestClass {\n");
    sb.append("    testclass: ").append(toIndentedString(testclass)).append("\n");
    sb.append("    bundle: ").append(toIndentedString(bundle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("testclass");
    openapiFields.add("bundle");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TestClass
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (TestClass.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in TestClass is not found in the empty JSON string", TestClass.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!TestClass.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TestClass` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("testclass") != null && !jsonObj.get("testclass").isJsonNull()) && !jsonObj.get("testclass").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `testclass` to be a primitive type in the JSON string but got `%s`", jsonObj.get("testclass").toString()));
      }
      if ((jsonObj.get("bundle") != null && !jsonObj.get("bundle").isJsonNull()) && !jsonObj.get("bundle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bundle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bundle").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TestClass.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TestClass' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TestClass> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TestClass.class));

       return (TypeAdapter<T>) new TypeAdapter<TestClass>() {
           @Override
           public void write(JsonWriter out, TestClass value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TestClass read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TestClass given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TestClass
  * @throws IOException if the JSON string is invalid with respect to TestClass
  */
  public static TestClass fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TestClass.class);
  }

 /**
  * Convert an instance of TestClass to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

