/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.TestClass;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TestClasses
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-23T09:56:25.063401+01:00[Europe/London]")
public class TestClasses {
  public static final String SERIALIZED_NAME_TESTCLASSES = "testclasses";
  @SerializedName(SERIALIZED_NAME_TESTCLASSES)
  private List<TestClass> testclasses = null;

  public TestClasses() {
  }

  public TestClasses testclasses(List<TestClass> testclasses) {
    
    this.testclasses = testclasses;
    return this;
  }

  public TestClasses addTestclassesItem(TestClass testclassesItem) {
    if (this.testclasses == null) {
      this.testclasses = new ArrayList<>();
    }
    this.testclasses.add(testclassesItem);
    return this;
  }

   /**
   * Get testclasses
   * @return testclasses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<TestClass> getTestclasses() {
    return testclasses;
  }


  public void setTestclasses(List<TestClass> testclasses) {
    this.testclasses = testclasses;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestClasses testClasses = (TestClasses) o;
    return Objects.equals(this.testclasses, testClasses.testclasses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testclasses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestClasses {\n");
    sb.append("    testclasses: ").append(toIndentedString(testclasses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("testclasses");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TestClasses
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (TestClasses.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in TestClasses is not found in the empty JSON string", TestClasses.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!TestClasses.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TestClasses` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("testclasses") != null && !jsonObj.get("testclasses").isJsonNull()) {
        JsonArray jsonArraytestclasses = jsonObj.getAsJsonArray("testclasses");
        if (jsonArraytestclasses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("testclasses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `testclasses` to be an array in the JSON string but got `%s`", jsonObj.get("testclasses").toString()));
          }

          // validate the optional field `testclasses` (array)
          for (int i = 0; i < jsonArraytestclasses.size(); i++) {
            TestClass.validateJsonObject(jsonArraytestclasses.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TestClasses.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TestClasses' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TestClasses> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TestClasses.class));

       return (TypeAdapter<T>) new TypeAdapter<TestClasses>() {
           @Override
           public void write(JsonWriter out, TestClasses value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TestClasses read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TestClasses given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TestClasses
  * @throws IOException if the JSON string is invalid with respect to TestClasses
  */
  public static TestClasses fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TestClasses.class);
  }

 /**
  * Convert an instance of TestClasses to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

