/*
 * Galasa Ecosystem API
 * The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.
 *
 * The version of the OpenAPI document: 0.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.WorklistItem;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Worklist
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-23T09:56:25.063401+01:00[Europe/London]")
public class Worklist {
  public static final String SERIALIZED_NAME_WORKLIST_ITEMS = "worklistItems";
  @SerializedName(SERIALIZED_NAME_WORKLIST_ITEMS)
  private List<WorklistItem> worklistItems = null;

  public Worklist() {
  }

  public Worklist worklistItems(List<WorklistItem> worklistItems) {
    
    this.worklistItems = worklistItems;
    return this;
  }

  public Worklist addWorklistItemsItem(WorklistItem worklistItemsItem) {
    if (this.worklistItems == null) {
      this.worklistItems = new ArrayList<>();
    }
    this.worklistItems.add(worklistItemsItem);
    return this;
  }

   /**
   * Get worklistItems
   * @return worklistItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WorklistItem> getWorklistItems() {
    return worklistItems;
  }


  public void setWorklistItems(List<WorklistItem> worklistItems) {
    this.worklistItems = worklistItems;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Worklist worklist = (Worklist) o;
    return Objects.equals(this.worklistItems, worklist.worklistItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(worklistItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Worklist {\n");
    sb.append("    worklistItems: ").append(toIndentedString(worklistItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("worklistItems");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Worklist
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (Worklist.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in Worklist is not found in the empty JSON string", Worklist.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Worklist.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Worklist` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("worklistItems") != null && !jsonObj.get("worklistItems").isJsonNull()) {
        JsonArray jsonArrayworklistItems = jsonObj.getAsJsonArray("worklistItems");
        if (jsonArrayworklistItems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("worklistItems").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `worklistItems` to be an array in the JSON string but got `%s`", jsonObj.get("worklistItems").toString()));
          }

          // validate the optional field `worklistItems` (array)
          for (int i = 0; i < jsonArrayworklistItems.size(); i++) {
            WorklistItem.validateJsonObject(jsonArrayworklistItems.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Worklist.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Worklist' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Worklist> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Worklist.class));

       return (TypeAdapter<T>) new TypeAdapter<Worklist>() {
           @Override
           public void write(JsonWriter out, Worklist value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Worklist read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Worklist given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Worklist
  * @throws IOException if the JSON string is invalid with respect to Worklist
  */
  public static Worklist fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Worklist.class);
  }

 /**
  * Convert an instance of Worklist to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

